### ISSUE TITLE
How to add styles (dropdown)?

### ISSUE THREAD

**Issue by mgordey** [stevdza-san/KotlinBootstrap#7]
I added (dropdown) to box layout and expected to see dropdown as in example, but as u see (my image) it doest have a style.
![image](https://github.com/stevdza-san/KotlinBootstrap/assets/93282399/a15c8f8f-5cf1-4a85-b0aa-a2ca0ca36b0d)

**Comment by stevdza-san** [comment]
What version of the library are you using?

**Comment by mgordey** [comment]
@stevdza-san 
I've fixed this bug by updating kobweb form kobweb = "0.15.1"
 to kobweb = "0.15.2" =). I didnt know that is so important.

**Comment by stevdza-san** [comment]
@mgordey Yes, with that new version now we don't have to add an extra style/link code for the bootstrap library, since it's already included.

**Comment by bitspittle** [comment]
@mgordey  This incompatibility was caused by a specific feature change that I implemented for the sake of this library actually. Sorry about that!

See also: https://github.com/varabyte/kobweb/issues/329

Moving forward, you shouldn't have to worry about what Kobweb version you are using. You should be able to load old Kobweb libraries with newer versioned applications, no problem.

That said, Compose versioning will be important, in case this library ever bumps up the Compose version at some point. The Compose version used by this library and by Kobweb have to be compatible.
